### ISSUE TITLE
INFOGRAFÍA-INGENERIA DE REQUISITOS

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/infografia-ElvisS10-1#3]
![INGENERIA-REQUISITOS_ELVIS](https://user-images.githubusercontent.com/72048969/111955877-b2497300-8aaf-11eb-8ca4-886fa8dbe54f.png)

**Comment by antoniio** [comment]
Excelente trabajo! La infografía esta bien diseñada
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
